<?php

namespace App\Controller\Admin;

use App\Entity\User;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Context\AdminContext;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\BooleanField;
use EasyCorp\Bundle\EasyAdminBundle\Field\ChoiceField;
use EasyCorp\Bundle\EasyAdminBundle\Field\DateField;
use EasyCorp\Bundle\EasyAdminBundle\Field\NumberField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use Symfony\Component\Security\Core\Security;

class UserCrudController extends AbstractCrudController
{
    private Security $security;

    public function __construct(
        Security $security)
    {
        $this->security = $security;
    }

    public static function getEntityFqcn(): string
    {
        return User::class;
    }

    public function configureCrud(Crud $crud): Crud
    {
        return $crud
            ->setEntityPermission('ROLE_SUPERADMIN');
    }

    public function configureFields(string $pageName): iterable
    {
        return [
            TextField::new('email'),
            TextField::new('name'),
            DateField::new('creationDate'),
            ChoiceField::new('roles')
                ->setChoices([
                    'Admin Role' => 'ROLE_ADMIN',
                    '[Default] User Role' => 'ROLE_USER',
                ])
                ->allowMultipleChoices(true)
        ];
    }

    public function index(AdminContext $context)
    {
        $user = $this->security->getUser();

        if (!$user) {
            return $this->redirect('/');
        }

        return parent::index($context); // TODO: Change the autogenerated stub
    }
}
